### ISSUE TITLE
Crashes Rubymine's "runs" on non-shadowenv projects

### ISSUE THREAD

**Issue by EtienneBerubeShopify** [Shopify/intellij-shadowenv#3]
Trying to execute a "run-config" for a rubymine project (not using shadow-env) and I get "Error running 'Run tests': Unknown error". 

Looking at the log confirms that the problem stems from the intellij-shadowenv plugin
```
2021-12-13 15:23:04,798 [ 141232]   INFO - xecution.runners.ExecutionUtil - Error running 'Run tests':<br>Unknown error 
java.lang.NullPointerException
	at java.base/java.lang.String.contains(String.java:2036)
	at com.shopify.shadowenv.products.rubymine.RubyMineRunConfigurationExtension.updateConfig(RubyMineRunConfigurationExtension.java:73)
	at com.shopify.shadowenv.products.rubymine.RubyMineRunConfigurationExtension.patchCommandLine(RubyMineRunConfigurationExtension.java:32)
	at com.shopify.shadowenv.products.rubymine.RubyMineRunConfigurationExtension.patchCommandLine(RubyMineRunConfigurationExtension.java:19)

```

**Comment by olfway** [comment]
Have same issue in Intellij Idea
